version: "3.3"

# To stop and remove the existing containers of same name with different images:
# docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)

services:

  #ZOOKEEPER CONFIGURATION
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: "echo stat | nc 192.168.99.100 $$ZOOKEEPER_CLIENT_PORT"

  #KAFKA BROKER CONFIGURATIION - FIRST INSTANCE
  kafka-1:
    image: confluentinc/cp-kafka:5.5.1
    container_name: kafka-1
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
      - "29091:29091"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9091,PLAINTEXT_HOST://192.168.99.100:29091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    healthcheck:
      test: [ "CMD", "nc", "-z", "192.168.99.100", "9091" ]

  #KAFKA BROKER CONFIGURATIION - SECOND INSTANCE
  kafka-2:
    image: confluentinc/cp-kafka:5.5.1
    container_name: kafka-2
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://192.168.99.100:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    healthcheck:
      test: [ "CMD", "nc", "-z", "192.168.99.100", "9092" ]

  # KAFKA MANAGER
  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:3.0.0.5
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
    healthcheck:
      test: "curl -f http://192.168.99.100:9000 || exit 1"